-- 8.
SELECT
       CLASS_NAME
     , PROFESSOR_NAME
    FROM TB_CLASS
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
    JOIN TB_PROFESSOR USING(PROFESSOR_NO);
    
-- 9.
SELECT
       CLASS_NAME
     , PROFESSOR_NAME
    FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
    JOIN TB_PROFESSOR USING(PROFESSOR_NO)
 WHERE CATEGORY = '인문사회';

-- 10.
SELECT
       학번 
     , "학생 이름"
     , "전체 평점"
     FROM (SELECT
                 STUDENT_NO 학번 
               , STUDENT_NAME "학생 이름"
               , ROUND(AVG(POINT), 1) "전체 평점"
               FROM TB_STUDENT
               JOIN TB_GRADE USING(STUDENT_NO)
               JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
               WHERE DEPARTMENT_NAME = '음악학과'
               GROUP BY STUDENT_NO, STUDENT_NAME)
    ORDER BY 1;
        
-- 11.
SELECT
       DEPARTMENT_NAME "학과이름"
     , STUDENT_NAME "학생이름"
     , PROFESSOR_NAME "지도교수이름"
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
    WHERE STUDENT_NO = 'A313047';
    
-- 12.
SELECT 
       STUDENT_NAME
     , TERM_NO
     FROM TB_STUDENT
     JOIN TB_GRADE USING(STUDENT_NO)
     JOIN TB_CLASS USING(CLASS_NO)
 WHERE TERM_NO LIKE '2007%'
    AND CLASS_NAME = '인간관계론';

-- 13.
SELECT 
       CLASS_NAME
     , DEPARTMENT_NAME
    FROM (SELECT 
               CLASS_NAME 
             , DEPARTMENT_NAME
             , PROFESSOR_NO
            FROM TB_CLASS
            LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
            LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
            WHERE CATEGORY = '예체능')
 WHERE PROFESSOR_NO IS NULL;

-- 14.
SELECT
       STUDENT_NAME "학생이름"
     , NVL((SELECT
                PROFESSOR_NAME
            FROM TB_PROFESSOR
            JOIN TB_STUDENT ON(PROFESSOR_NO = COACH_PROFESSOR_NO)), '지도교수 미지정') "지도교수"
    FROM TB_STUDENT
    WHERE DEPARTMENT_NO = '020'
    ORDER BY STUDENT_NO;

-- 15.
SELECT
       STUDENT_NO 학번
     , STUDENT_NAME 이름
     , DEPARTMENT_NAME "학과 이름"
     , ROUND(AVG(POINT), 8) 평점
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
    WHERE ABSENCE_YN = 'N'
    GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
    HAVING ROUND(AVG(POINT), 8) >= 4.0
 ORDER BY 1;

-- 16.
SELECT
       CLASS_NO
     , CLASS_NAME
     , ROUND(AVG(POINT), 8)
     FROM TB_GRADE
     JOIN TB_CLASS USING(CLASS_NO)
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '환경조경학과'
        AND CLASS_TYPE LIKE '전공%'
    GROUP BY CLASS_NO, CLASS_NAME
 ORDER BY 1;

-- 17.
SELECT
       STUDENT_NAME
     , STUDENT_ADDRESS
    FROM TB_STUDENT
 WHERE DEPARTMENT_NO = (SELECT 
                           DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');
 
-- 18.
SELECT 
       STUDENT_NO
     , STUDENT_NAME
    FROM (SELECT
                STUDENT_NO
              , STUDENT_NAME
              , AVG(POINT)
              FROM TB_STUDENT
              JOIN TB_GRADE USING(STUDENT_NO)
              JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
              WHERE DEPARTMENT_NAME = '국어국문학과'
              GROUP BY STUDENT_NO, STUDENT_NAME
              ORDER BY 3 DESC)
    WHERE ROWNUM = 1;

-- 19.
SELECT
       DEPARTMENT_NAME "계열 학과명"
     , ROUND(AVG(POINT), 1) "전공평점"
    FROM TB_DEPARTMENT
    JOIN TB_STUDENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
    WHERE CATEGORY = (SELECT
                           CATEGORY
                         FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '환경조경학과')
    GROUP BY DEPARTMENT_NAME
    ORDER BY 1;
